### ISSUE TITLE
Redirecting from wildcard matchers results in 404s

### ISSUE THREAD

**Issue by idlefingers** [frontarm/navi#105]
I'm trying to use a wildcard route to lazily load a set of 'admin' routes if the user is logged in and has the correct roles. I saw #60 which looked basically like what I'm trying to do, and if I understand how the issue ended correctly, it should work?

Given a 'main' route like this, when you go to '/admin' and you're not logged in, I'd expect the login redirect to trigger, but instead it raises 404 exceptions.

```js
const routes = mount({
  "/login": route({
    view: <div>Login</div>
  }),

  "*": map(async (request, context) => {
    // If loggedIn is false, all the lazily loaded admin routes
    // throw a 404 error, rather than redirecting to login
    const loggedIn = false;

    if (!loggedIn) {
      return redirect("/login");
    }

    return mount({
      "/admin": lazy(() => import("./admin"))
    });
  })
});
```

I made an example codesandbox [here](https://codesandbox.io/s/navi-wildcard-redirect-rvb5d?expanddevtools=1&fontsize=14&hidenavigation=1&initialpath=%2Fadmin)

Am I just misinterpreting the docs, or is this possible, or is it a bug? 🤔

**Comment by jamesknelson** [comment]
If it's not too late for this, the trick here is that you'll need to tell `redirect()` that it can match anything:

```js
if (!loggedIn) {
  return redirect("/login", { exact: false })
}
``` 

I've been confused by this myself at times. Would definitely be keen to hear any ideas for improving the match heuristics.
