### ISSUE TITLE
Weird URL matching issue

### ISSUE THREAD

**Issue by remotealex** [frontarm/navi#109]
Hello! So I think I've just found a bug with URL matching in navi, but perhaps I have have a misunderstanding of the matching rules for routes. I think a use case is the easier way to illustrate:

In my app I have this setup:

Route for `/plan`
...other routes...
Route for `/:username` last

If someone has the username "planb" though, navi matches that as `/plan/b` and my app 404s as that isn't valid 

Here's a codesandbox which shows it: https://codesandbox.io/s/wonderful-sound-pe2g7

**Comment by jamesknelson** [comment]
Doh, this is definitely a bug. Will investigate now.

**Comment by jamesknelson** [comment]
Just published a fix for this on 0.12.10 and 0.13.0-beta.1

**Comment by remotealex** [comment]
Amazing. Thanks!
