### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by viniciuscr** [frontarm/navi#116]
I have been struggling to create my simple app with navi because the documentation looks very confusing.
There are some code examples without a context on the route page and a lot of vague ideas about how to use it.
 I would like a example with dynamic side menu, where it would change according with the route.
I tried pass some information on the context but it only show after accessing the url a second time.

I would like to know what happens and when to figures out the better moment to try insert some context and send it from one view to another.

It says the <View /> would be filled with the content of the first match. I assumed if I had more then a match or a list of view on a single match it would be inserting the content on each <View /> but it actually repeats the same content on all <View />.

some examples have a "fragment" prop on the route object, but there is no example or information about what is it.

**Comment by jamesknelson** [comment]
Hi @viniciuscr,

There's an example with a navbar header with active link styles on this page: https://frontarm.com/navi/en/guides/nested-views/

Regarding context, you generally don't want to pass data to views via Navi context. Just use React props and React context. The main reason for Navi context is when you want to make views that vary based on something like authentication. For details, see this page: https://frontarm.com/navi/en/guides/routing-context/

As for fragments - if you're not sure what fragments are yet, check this page out in the React documentation: https://reactjs.org/docs/fragments.html

If you'd like to take a stab at improving the documentation, I'd love to see what you can come up with!
