### ISSUE TITLE
SSR: TS2304: Cannot find name 'ScrollBehavior'.

### ISSUE THREAD

**Issue by kettanaito** [frontarm/navi#117]
When I have the next SSR setup:

```tsx
import { createMemoryNavigation } from 'navi'
import { Router, View } from 'react-navi'

// ...

   const navigation = createMemoryNavigation({
      routes,
      url: request.url,
    })

    const route = await navigation.getRoute()

    const clientMarkup = renderToString(
      <Router navigation={navigation}>
        <View />
      </Router>,
    )
```

The server build via webpack produces the next TypeScript (awesome-typescript-loader) exception:

```
ERROR in [at-loader] ./node_modules/react-navi/dist/types/HashScroll.d.ts:3:55 
    TS2304: Cannot find name 'ScrollBehavior'.
```

The error concerns this reference:

```ts
// react-navi/dist/types/HashScroll.d.ts:3:55 
export declare const HashScrollContext: React.Context<ScrollBehavior>;
export interface HashScrollProps {
    behavior?: HashScrollBehavior;
    children: React.ReactNode;
}
```

`ScrollBehavior` type itself is a built-in type from the `dom` TypeScript library.

## Current behavior

That type is required during the server build.

## Expected behavior

Static (SSR) rendering does not reference client-side types.

---

I may dig deeper into this issue, but can't promise any deadlines. If you have any out-of-head insights it would be very appreciated. Thank you.

**Comment by jamesknelson** [comment]
I feel like the easiest way to solve this is to redefine ScrollBehavior locally, so add something like this to the top of that file:

```typescript
type ScrollBehavior = 'auto' | 'smooth'
```

Feel like giving this a go?

**Comment by kettanaito** [comment]
I was trying to provide that manual type on local, but I've found that source code already uses an explicit `HashScrollBehavior`:

https://github.com/frontarm/navi/blob/ff90816c188244e032a37188d8ad201a67ff42d7/packages/react-navi/src/HashScroll.tsx#L3-L7

Is this a types compilation issue then, so it ends up a native `ScrollBehavior` after the compilation? Or, perhaps, type definitions published are outdated?

**Comment by jamesknelson** [comment]
Wow, that's odd. It must be a compilation issue, because the types are compiled on every release.

I can see if I can find a workaround for this, but before I do, could you try changing it in your node_modules directory and see if that's enough to make TypeScript compile on the server? There's also some `window` references in that file that I imagine may cause issues on the server.

**Comment by kettanaito** [comment]
I confirm that manually changing that problematic reference to `ScrollBehavior` to `HashScrollBehavior` (as in the source code) fixed the compilation error. At the moment there are no other errors, so I'm able to compile server and client gracefully.

I hope it's an issue of types compilation. Please let me know what that was.

**Comment by jamesknelson** [comment]
Closing, as this appears to be fixed in the latest release.
