### ISSUE TITLE
Help with types

### ISSUE THREAD

**Issue by lookfirst** [frontarm/navi#128]
Apologies, I know this is an issue tracker, but I didn't immediately see a way to ask a question. Plus, this discussion might help others.

```
const authSection = (authRoute: any) => compose(
	withView((_, context: RoutingContext) => (
		<MainLayout user={context.currentUser}/>
	)),
	compose(
		withView(
			<>
				<AuthenticationHeader/>
				<MainWithView/>
			</>
		),
		authRoute
	)
);
```

authRoute is this...

```
export default route({
	getView: () => {
		return (<Users/>);
	},
	title: 'Authentication - Users',
});
```

What type should I use for the `any` in authSection? If I don't use `any` there, I get the usual implicityany error.

**Comment by jamesknelson** [comment]
I *think* you want `Matcher<RoutingContext>`.

**Comment by lookfirst** [comment]
Perfect, thanks!
