### ISSUE TITLE
variable number of URL params

### ISSUE THREAD

**Issue by bryndyment** [frontarm/navi#129]
My app has nested projects:

`/group/project`
`/group/subgroup/project2`
`/group/subgroup/subgroup/project3`

etc.

Given the above `originalUrl` I am able to successfully match to my project view, but I am getting `Page Not Found` if I don't have an exact match of URL parameters.

E.g.:

`/group/project`
`/group2/project2`
`/group3/subgroup1/project3`

… will only match `project` and `project2` with a `/:one/:two` route key, and will only match `project3` with a `/:one/:two/:three` route key.

I am not even using the URL parameters in the above case, as I'm able to determine my project just with the `originalUrl` string.

I have tried to use the `'*'` wildcard but I'm getting `Page Not Found` for all projects in that case.

Any clues as to how I should be approaching the above routing?

**Comment by jamesknelson** [comment]
I'm not sure I understand exactly the requirements here. Is the issue that you do not know how deeply the paths will be nested?

**Comment by bryndyment** [comment]
Pretty much yes!

I guess I can summarize it as follows.  I want to determine the view based solely on `originalUrl`, which can contain arbitrarily deep nesting of user-provided group slugs, subgroup slugs, and project slugs.

I want the entire URL string (which `originalUrl` gives me) and can determine the view based solely on that, but, as you said, there is an arbitrary depth to the paths.

**Comment by jamesknelson** [comment]
So this is a bit of a hack, but I think this may work?

```
map(req => {
  return mount({
    [getMyPath(req.originalUrl)]: route(
      //...
    )
  })
})
```

**Comment by bryndyment** [comment]
Thanks … I will try this.  What is `getMyPath`, though?

**Comment by jamesknelson** [comment]
Glad that it works!

getMyPath was just a placeholder for transforming the URL however you want, but if it works without it then that’s great :-)

Will close for now as this seems resolved.
