### ISSUE TITLE
use navigation.navigate inside useffect

### ISSUE THREAD

**Issue by abdelav** [frontarm/navi#130]
Hi, I was trying to redirect to another view when a state changes with useEffect(), but when `navigation.navigate('/something')` is triggered I got a react warning:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
is there something I am missing? maybe call an unsubscribe method for navigation?

here is the code:

```jsx
import React, { useEffect } from 'react';
import injectSheet from 'react-jss';
import { useNavigation } from 'react-navi';

// Local Modules
// import Modal from '../../components/modal';
import Styles from './styles';

// Stores
import authStore from '../../stores/auth';

// Icons
import logo from './icons/logo.svg';

function Login ({ classes }) {
  const [authState, authActions] = authStore();
  const navigation = useNavigation();
  const { authenticated } = authState;
  useEffect(() => {
    if (authenticated) {
      navigation.navigate('/')
    }

    return () => {
      console.log('unmount');
    }
  }, [authenticated, navigation]);

  return (
    <div className={classes.container}>
      <div className="loginBox">
        <img alt="logo" src={logo} />
        <h1>Iniciar sesión</h1>
        <div className="input">
          <label>Usuario</label>
          <input {...{
            type     : 'text',
            value    : authState.credentials.email,
            onChange : (event) => authActions.updateField('email', event.target.value),
          }} />
        </div>

        <div className="input">
          <label>Contraseña</label>
          <input {...{
            type     : 'password',
            value    : authState.credentials.password,
            onChange : (event) => authActions.updateField('password', event.target.value),
          }} />
        </div>

        <div className="formControls">
          <div>
            <p>Recuperar contraseña</p>
            <p>Crear cuenta</p>
          </div>
          <div>
            <div className="btn" onClick={() => authActions.authenticate()}>
              Iniciar sesión
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default injectSheet(Styles)(Login);
```

thanks in advance!

**Comment by lookfirst** [comment]
The issue is that you're thinking of login like a classic client/server webapp where you do an action and then redirect to the logged in page.

You need to think in a different way for single page apps. You have a render loop which is controlled by the router at the top level and you want the screen to render a view based on a state. In this case the state is whether or not the user is logged in or not.

In this case, you perform an action, login, and then the success of that action changes the state. that the user is logged in. This should cause a render loop update and display the new logged in view. No 'redirect' is necessary.

Follow the guide here: https://frontarm.com/navi/en/guides/authenticated-routes/

**Comment by lookfirst** [comment]
Another way to think about this separation of concerns. The Login component shouldn't know anything about navigation. All it should do is render the form. The form has a button on it, which when clicked, executes a function that is passed in. The component which is displayed after login is not the login components concern.

**Comment by abdelav** [comment]
thank you!
