### ISSUE TITLE
Routes getting called multiple times during page load

### ISSUE THREAD

**Issue by lookfirst** [frontarm/navi#133]
I'm finally starting to add some getData() methods to my routes. Throwing a console.log() in there shows that it is getting called many 3-4 times during a page refresh. Obviously, I'm not going to want to query my database that many times, especially since it is firestore and costs real money, so what can I do to prevent this? Or maybe a better question is, what am I doing wrong that causes this function to get called so many times?

**Comment by lookfirst** [comment]
Update: I think I figured out a bit of it. I'm updating the context with global user state, so that is causing the route updates. That said, I guess what I'd still like to know is how to maybe skip updates. I'm not sure I can get rid of all of them easily. I guess I can cache the data internally, but then it becomes an issue of knowing when to skip the cache. Ugh.

**Comment by jamesknelson** [comment]
On my phone atm so haven’t got an example on hand, but It’s possible to cache state using the state property of our route options, and then check request.state.

This works for things like only calling the server once even over multiple renders. I’m still not 100% counted if the API though, so it should be considered experimental. This is one of the main things that need to be solved before releasing 1.0.

**Comment by lookfirst** [comment]
@jamesknelson Thank you for the fast answer, especially from your phone! =)

Thanks for the tip. Once again, really impressed with your router, once you wrap your brain around it, things are really easy to reason on and resolve.

I resolved this by reworking the code that tells if I'm logged in or not and logging the user, as well as what I'm putting into the RouterContext. Therefore, I only do one context update instead of like 4. I can see now that the `getData()` method is only being called once. This had the nice benefit of really speeding up app loading times (obviously).

To explain, I have a `useState()` object that creates my `Person` class and I throw that into the `RouterContext` early on. Within that class, it gets filled out with async `useEffect(, [])` data like whether the user is logged in. I also put the `setPerson` method from `useState()` within the `Person` class as well. This way, I can easily implement `person.logout()` => `this.setPerson(new Person())`, which forces the update. I do what you suggested before and copy the RouterContext into a React Context, which gives it to me way down in my component tree with a simple `useSessionContext()`.

I think one interesting internal developer-only feature would be to warn people in the console if they are getting a lot of fast renders on the same path. Of course default this as `false`, since I can predict the number of open issues it would cause. =)

Another thing is why isn't there a `useRouterContext()` that returns the context passed into the route?

I call it SessionContext here, but it should effectively just be the `<Router>` context.

```
import React, {useContext} from "react";
import {RoutingContext} from "../types/RoutingContext";

export const SessionContext = React.createContext<Partial<RoutingContext>>({});

interface SessionProviderProps {
	value: RoutingContext,
	children: React.ReactNode | React.ReactNode[],
}

export function useSessionContext() {
	const context = useContext(SessionContext);
	if (!context) {
		throw new Error('useSessionContext must be used within a SessionProvider');
	}
	return context;
}

export const SessionProvider = ({value, children}: SessionProviderProps) => (
	<SessionContext.Provider value={value}>
		{children}
	</SessionContext.Provider>
);
```

**Comment by jamesknelson** [comment]
> I think one interesting internal developer-only feature would be to warn people in the console if they are getting a lot of fast renders on the same path. Of course default this as false, since I can predict the number of open issues it would cause. =)

I agree, this would be really nice. Would happily accept a PR ;)

> Another thing is why isn't there a useRouterContext() that returns the context passed into the route?

That's an interesting question. I've thought about adding something like this before, although there's been something holding me back and I can't even remember what it is.

**Comment by lookfirst** [comment]
Closing, no point in leaving open.
