### ISSUE TITLE
[feature] useRequest

### ISSUE THREAD

**Issue by lookfirst** [frontarm/navi#134]
I found that I needed `mountpath` everywhere for making links. Not sure why you don't include something like this.

I am so loving this react provider api + hooks. Before working on this project, I adopted something similar in a flutter app and it makes building components so much easier.

```ts
import * as React from 'react';
import {ReactNode, createContext, useContext} from "react";

import {NaviRequest} from "navi";

export const RequestContext = createContext<NaviRequest | undefined>(undefined);

interface RequestProviderProps {
	value: NaviRequest,
	children: ReactNode | ReactNode[],
}

export function useRequest() {
	const context = useContext(RequestContext);
	if (!context) {
		throw new Error('useRequest must be used within a RequestContextProvider');
	}
	return context;
}

export const RequestContextProvider = ({value, children}: RequestProviderProps) => {
	return (
		<RequestContext.Provider value={value}>
			{children}
		</RequestContext.Provider>
	)
};
```

**Comment by jamesknelson** [comment]
Thanks for the idea!

It's pretty clear what `useRequest()` should do, which is nice. I think it would be a useful thing to have, although I'm not convinced yet that it needs to be part of Navi itself. It's easy enough to add application-side if you need it, and I haven't found myself using it within most of my projects that use Navi.

At minimum, it would probably make sense to add something like this to the docs. I'm not sure I have a strong enough opinion either way though. Would love to hear feedback from others.

**Comment by lookfirst** [comment]
> I haven't found myself using it within most of my projects that use Navi.

How do you access the request data within a View component? Just pass it in the props?

I just coded that up and it does seem simpler. The only bummer is that looking at the `<Edit>` component externally, it is hard to 'see' exactly what is required within it.

```
interface RequestProps {
   request: NaviRequest;
}

export default route({
	getView: (request) => <Edit request={request}/>,
	title: 'Invoices - Edit',
});

function Edit({request: {mountpath, params}}: RequestProps) {
```

I could just pass what it needs I guess, but also ugly. Happy for suggestions.

Also, closing this as it doesn't need to be an open issue.

**Comment by jamesknelson** [comment]
> How do you access the request data within a View component? Just pass it in the props?

Yep, I've just been passing it via props. If I want to access something deeper, I'll throw specific parts into React context at the top of the tree, and then access it via that.

For an example, take a look at the Navi site's routes:

https://github.com/frontarm/navi-website/blob/master/src/routes.js

**Comment by lookfirst** [comment]
@jamesknelson Ok, that works. One thing that would be nice is if the router exposed what the mount paths were so that I didn't have to manually pass them down the tree. For example, and maybe this is not correct, but I have these two browser urls:

```
/invoices <- list all invoices
/invoices/edit  <- create new invoice
/invoices/edit/ID <- edit existing invoice
```

The idea being that I'm either creating or updating an existing invoice.

On the create/edit page, I have a link to go back to the /invoices route, but it would be nice to not have to hand pass down the mountpath. I borrowed some of your code in one of the examples:

```
export function makeRootContext(aRoute: any) {
	return compose(
		withContext((req, context): AppContext => ({
			...context,
			root: req.mountpath,
		})),
		aRoute
	);
}
```

Luckily that context change doesn't seem to cause another render.

**Comment by jamesknelson** [comment]
> One thing that would be nice is if the router exposed what the mount paths were so that I didn't have to manually pass them down the tree.

I'm not sure how this could be done automatically, unless the mount paths of each `mount()` are put in an array. But then you need to know the depth of the specific mount you want.

I feel like the way you're doing it with adding `root` to context is probably the best approach. The `withContext` matcher never creates any extra renders. What probably would make sense is an easier way to add things to context (as opposed to replacing the context).

**Comment by lookfirst** [comment]
Right, the depth is a hard one, but something that exposed what depth I'm currently at in the path tree would be nice.

`/foo/bar/ack`

When I'm in the view for `/ack`, I'd like to be able to get the parent path.  Like the ability to walk back up the tree without having to expose the tree myself. Not the end of the world for this stuff, just something to think about.
