### ISSUE TITLE
useHistory() - Deprecation Warning: "useHistory()" is deprecated. It will be removed in a future version.

### ISSUE THREAD

**Issue by alexvandervegt** [frontarm/navi#137]
I have the following warning:

Deprecation Warning: "useHistory()" is deprecated. It will be removed in a future version.

Currently I have HOC

```
import {useCurrentRoute, useHistory} from 'react-navi';
import React from 'react';

const withCurrentRoute = (Component) => {
    return function WrapperComponent(props) {
        let route = useCurrentRoute();
        let history = useHistory();

        return <Component {...props} route={route} history={history} />;
    };
};

export default withCurrentRoute;
```

What should be used in the next version?

**Comment by jamesknelson** [comment]
Use `useNavigation()` instead. This returns a navigation object with `navigate()` and `subscribe()` methods.

See docs here:

- https://frontarm.com/navi/en/reference/react-components-hooks/#usenavigation
- https://frontarm.com/navi/en/reference/navigation/

**Comment by alexvandervegt** [comment]
Thanks!
