### ISSUE TITLE
Couldn't find window.NaviScripts

### ISSUE THREAD

**Issue by fogost** [frontarm/navi#141]
Hi, when i run `yarn build` this happens.
<img width="1440" alt="Снимок экрана 2019-09-27 в 23 48 11" src="https://user-images.githubusercontent.com/5126657/65801310-7b77f280-e181-11e9-8be8-a69d94437345.png">
Why is this happening?

**Comment by jamesknelson** [comment]
Not sure what's happening here -- have you tried to call `getRandomValues()` anywhere within your code?

**Comment by jamesknelson** [comment]
Closing this for now due to lack of reply.
