### ISSUE TITLE
junctions

### ISSUE THREAD

**Issue by lookfirst** [frontarm/navi#145]
https://github.com/frontarm/navi/blob/gh-pages/CNAME

**Comment by jamesknelson** [comment]
Oops. Navi used to be called junctions, I must have forgotten to remove this file when renaming. 

Probably the best thing is just to remove the gh-pages branch, since the docs are now in a separate repository. Thanks for pointing it out!

**Comment by lookfirst** [comment]
navi is a much better name. =)
