### ISSUE TITLE
[feature] Add documentation for deploying navi as a SPA on github pages

### ISSUE THREAD

**Issue by lookfirst** [frontarm/navi#146]
My specific quandry is how to figure out how to create the folder structure in navi without having to hard code it. How do I add the /mui-rff/ path and keep all the links working?

Here is where I'm working out of...

https://lookfirst.github.io/mui-rff/
https://github.com/lookfirst/mui-rff

**Comment by jamesknelson** [comment]
I'm not sure exactly what you mean, but it might be worth taking a look at how create-react-blog imports a directory of files without manually specifying each one. It uses the import-all babel macro, although you can also accomplish the same thing with webpack contexts:

https://github.com/jamesknelson/create-react-blog/blob/master/template/src/routes/posts/index.js

**Comment by lookfirst** [comment]
yea, sorry... i ended up changing everything around and forgot to close this today. sorry for wasting your time.
