### ISSUE TITLE
Huge import size.

### ISSUE THREAD

**Issue by asimashfaq** [frontarm/navi#151]
Webpack adding huge size to the production bundle.
https://prnt.sc/pwcf5i

Any suggestions to reduce this.

my `tsconfig.json`

`{
  "compilerOptions": {
      "outDir": "./dist/",
      "sourceMap": true,
      "noImplicitAny": false,
      "jsx": "react",
      "module": "esnext",
      "esModuleInterop":true,
      "isolatedModules": true,
      "moduleResolution": "node",
      "target": "es5",
      "lib": [      
        "es5",
        "es6",
        "dom",
        "dom.iterable",
        "es2015.collection",
        "es2017"]
  },
  "include": [
      "./src/**/*", "tests/venue/reducer.test.ts", "tests/venue/action.test.ts", "tests/venue/epic.test.ts", "tests/services/api.test.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
      "reportFiles": [
          "./src/**/*"
      ]
  }
}`

**Comment by jamesknelson** [comment]
Closing this as I'm not sure a gzipped size of 11kb is really "huge".
