### ISSUE TITLE
Prefetch on hover

### ISSUE THREAD

**Issue by nhooyr** [frontarm/navi#157]
I'm using onMouseHover on my Links to prefetch components. It'd be nice if Link could support this natively with a boolean option.

navi could also cancel the request if the user has moved their mouse away.

**Comment by nhooyr** [comment]
At the very least we need to add a field for onMouseHover in LinkProps.

**Comment by nhooyr** [comment]
Should just accept all HTML element props.

**Comment by jamesknelson** [comment]
> Should just accept all HTML element props.

I agree. Will see what I can do.

**Comment by nhooyr** [comment]
Thank you @jamesknelson <3

**Comment by kirelagin** [comment]
For anyone searching around why their `target="_blank"` or `target="parent"` don’t work, these commits fixed that too.

**Comment by kirelagin** [comment]
@jamesknelson You might also be interested in how react-router does this: since recently they added a check for `target="_self"`: https://github.com/ReactTraining/react-router/blob/f31bb27aa61dd4cb1c3cd9aa78133f739e2e9bb9/packages/react-router-dom/modules/Link.js#L43
