### ISSUE TITLE
Lazy import not working with CRA 3.4

### ISSUE THREAD

**Issue by gut4** [frontarm/navi#173]
Looks like import is broken with CRA.
Js chunk is generated but not rendered.
I try dev and production.
– dev show NotFoundError: URL not found: /test
– production render nothing

`test.js`
```
export default mount({
  '/:id': route({
    view: <div>test page</div>
  })
})
```
`app.js`
```
const routes =
mount({
    '/test': lazy(() => import('./test')),
  })
```

```
function App () {
  return (
<Router routes={routes}>
      <Suspense fallback={null}>
        <View />
      </Suspense>
    </Router>
)}
```

**Comment by jamesknelson** [comment]
In this case, I think the reason that `/test` isn't being found, is that you've got no wildcard pattern on the `mount()` in test.js. Something like `/test/hello` will work, but `/test` by itself is still a 404.
