### ISSUE TITLE
TypeError: resolvable is not a function

### ISSUE THREAD

**Issue by brekk** [frontarm/navi#40]
I found this library via [a tutorial on Zeit](https://zeit.co/blog/painless-routing-react-navi-now), I'm pretty pleased with the clarity and ease-of implementation so far, so thank you very much!

I recently was hit with this simple and I imagine easy-to-fall-into mistake:

```js
export default createSwitch({
  paths: {
    "/": createPage({
      title: `home`,
      getContent: () => import("./Home")
    }),
    "/test": {
      title: "this is a test",
      getContent: () => import("./TestPage")
    }
})
```

☝️ So I'm missing a `createPage` wrapping on the `/test` property.

Because of that, when I try to go to `/test`, I see an error:

```
TypeError: resolvable is not a function
  Resolver.resolve
  node_modules/navi/dist/es/Resolver.js:54
```

I'd prefer to see some kind of error like:
```
Given path "/test" is not a valid path. Provided path should be one of Switch, Page, Redirect or Context. See https://frontarm.com/navi/reference/declarations/#declaring-pages for more info.
```

I don't have enough context to know whether this would be a reasonable change, but I spend a few minutes tracking this down and it seems like it'd be a common enough mistake for others to run into.

Thanks for your time and thanks for this project -- excited to use it more in the future!

<hr />

For myself I wrapped the paths property with a `map(createPage)`:
<details>

```js
import {map} from 'ramda'
export default createSwitch({
  paths: map(createPage, { '/': blah, '/test': blah})
})
```

So that I can avoid that potential footgun, but likely more complicated pages would require more nuance.

</details>

**Comment by jamesknelson** [comment]
Thanks for pointing this out -- it's a great idea that I would have totally missed.

It should be reasonably simple -- the `createSwitch` function already does a bit of sanity checking, and it should be possible to implement by just calling `instanceof` on each path. If you want to put together a PR that'd be amazing, otherwise I'll find some time to add this in the next couple weeks.

**Comment by jamesknelson** [comment]
I should mention that in addition to pages, you can also assign redirects, nested switches and contexts -- which is why there needs to be a `createPage` call instead of a plain old object. You can see the details [here](https://frontarm.com/navi/reference/declarations/).

**Comment by brekk** [comment]
@jamesknelson I should have some time for a PR in the next few weeks, more than happy to put some time in.

**Comment by jamesknelson** [comment]
Awesome! I’ll leave it for you for a couple weeks then. If you have any questions just give me a shout here.
