### ISSUE TITLE
A way to programatically push to a new route from within a component

### ISSUE THREAD

**Issue by samjbmason** [frontarm/navi#44]
I know this has been bought up in #29 but the solution there seems to be outdated. Is there a way to push to a new route as the result of an async request e.g a form submission.

**Comment by jamesknelson** [comment]
Thanks for asking! This changed in 0.8, and I really should add a guide to the docs website.

Your app's `navigation` object has a `history` property, which contains a [History](https://www.npmjs.com/package/history) object that can be used for programmatic navigation:

```js
navigation.history.push('/home', { some: 'state' })
navigation.history.replace('/login')
```

You can access `history` either directly on you `navigation` object, or you can use the `<NavHistory>` component exported by `react-navi` to access it in a React component:

```jsx
import { NavHistory } from 'react-navi'

function Form(props) {
  return (
    <NavHistory children={history =>
      <FormImpl history={history} {...props} />
    } />
  )
}

function FormImpl({ history, ...props }) {
  // ...
}
```

**Comment by samjbmason** [comment]
Thanks so much for the response I was meaning to close this as I saw that it was documented in the “Navi with React” section

**Comment by jamesknelson** [comment]
Thanks for letting me know! I think it'd be helpful to have a short "programmatic navigation" guide, so I'm going to reopen this until it's added.

**Comment by jamesknelson** [comment]
Have just added this guide as part of the 0.11 docs.
