### ISSUE TITLE
When using react hooks in pages and using getContent and error throws

### ISSUE THREAD

**Issue by samjbmason** [frontarm/navi#46]
I have noticed an issue when using the latest react version `16.8.0-alpha.0` that when i use getContent and do a dynamic import to a page that contains a hook it will blow up with this error:
`Hooks can only be called inside the body of a function component.`

Has anyone else seen this? And is there a current fix. I have found that I can get around it by using `content ` and getting the page as a React component but I wonder if thats a great idea as I assume it then pulls in every page on load

**Comment by jamesknelson** [comment]
I’ve seen this with static rendering and am working on a fix, but it’s news to me if it’s happening during development.

Probably what’s happening here is that are somehow two copies of react being bundled, one on the split code, and one in the host code.

Any chance you could post a minimal reproduction as a gist or with codesandbox?

**Comment by jamesknelson** [comment]
Closing this for now. Feel free to re-open if you haven't found a solution.
