### ISSUE TITLE
Slashes at end of URLs

### ISSUE THREAD

**Issue by jdiamond** [frontarm/navi#56]
Is there a way to avoid the "/" characters getting added to my URLs?

In this sandbox, click on the /page1 or /page2 links and you will see the URL change to /page1/ or /page2/. Happens in my own app, too.

https://codesandbox.io/s/n7v5o7j310

All the code:

```
import React from "react";
import ReactDOM from "react-dom";
import { mount, route } from "navi";
import { Router, Link } from "react-navi";

import "./styles.css";

const routes = mount({
  "/": route({
    view: () => (
      <p>
        Home. Go to <Link href="/page1">page 1</Link> or{" "}
        <Link href="/page2">page 2</Link>.
      </p>
    )
  }),
  "/page1": route({
    view: () => (
      <p>
        Page 1. Go <Link href="/">home</Link> or to{" "}
        <Link href="/page2">page 2</Link>.
      </p>
    )
  }),
  "/page2": route({
    view: () => (
      <p>
        Page 2. Go <Link href="/">home</Link> or to{" "}
        <Link href="/page1">page 1</Link>.
      </p>
    )
  })
});

function App() {
  return (
    <div className="App">
      <Router routes={routes} />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by jamesknelson** [comment]
Currently there's no way to avoid this as the trailing `/` is hard-coded in a few places, but I think it'd be possible to make it optional with a pretty small patch. You'd just need to add an `ensureTrailingSlash` option to `createBrowserNavigation` and `createMemoryNavigation`, and then pass it through to these places:

- https://github.com/frontarm/navi/blob/master/packages/navi/src/CurrentRouteObservable.ts#L130
- https://github.com/frontarm/navi/blob/master/packages/navi/src/URLTools.ts#L71
- https://github.com/frontarm/navi/blob/master/packages/navi/src/Chunks.ts#L155

It looks like this should work based on a quick hack. The tests pass other than a few strings that differ by a final slash.

Would you be interested in submitting a PR for this?

**Comment by jdiamond** [comment]
I started to see if I could do this. Forked, cloned, installed yarn, ran `yarn` and `yarn run test` and see these test failures. Is there a guide to setting up a dev environment or a way to make it work out of the box?

```
$ yarn run test
yarn run v1.13.0
$ lerna run --stream test
lerna notice cli v3.10.7
lerna info Executing command in 2 packages: "yarn run test"
navi: $ jest
navi: PASS test/MemoryNavigation.test.ts
navi: PASS test/ViewMatcher.test.ts
navi: PASS test/Basename.test.ts
navi: PASS test/Integration.test.ts
navi: PASS test/MountMatcher.test.ts
navi: PASS test/NotFound.test.ts
navi: PASS test/RedirectMatcher.test.ts
navi: PASS test/BrowserNavigation.test.ts
navi: PASS test/Router.test.ts
navi: Test Suites: 9 passed, 9 total
navi: Tests:       25 passed, 25 total
navi: Snapshots:   0 total
navi: Time:        2.633s, estimated 9s
navi: Ran all test suites.
react-navi: $ jest
react-navi: FAIL test/View.test.tsx
react-navi:   ● Test suite failed to run
react-navi:     Cannot find module 'navi' from 'View.test.tsx'
react-navi:     > 1 | import { createMemoryNavigation, compose, withView, route, mount } from 'navi'
react-navi:         | ^
react-navi:       2 | import React, { Component } from 'react'
react-navi:       3 | import ReactTestRenderer from 'react-test-renderer'
react-navi:       4 | import { View, NaviProvider } from '../src'
react-navi:       at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:221:17)
react-navi:       at Object.<anonymous> (test/View.test.tsx:1:1)
react-navi: FAIL test/Router.test.tsx
react-navi:   ● Test suite failed to run
react-navi:     Cannot find module 'navi' from 'Router.test.tsx'
react-navi:     > 1 | import { route, mount } from 'navi'
react-navi:         | ^
react-navi:       2 | import React from 'react'
react-navi:       3 | import ReactTestRenderer from 'react-test-renderer'
react-navi:       4 | import { Router } from '../src'
react-navi:       at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:221:17)
react-navi:       at Object.<anonymous> (test/Router.test.tsx:1:1)
react-navi: Test Suites: 2 failed, 2 total
react-navi: Tests:       0 total
react-navi: Snapshots:   0 total
react-navi: Time:        1.571s
react-navi: Ran all test suites.
react-navi: error Command failed with exit code 1.
react-navi: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 1 in 'react-navi'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jamesknelson** [comment]
You'll also need to do a `lerna bootstrap` before `yarn` and `yarn test`.

Also, to start with it's probably easiest to cd into packages/navi and just do `yarn test` there.

No guide yet, but I've put writing one on today's todos. Will leave a link once it's done.

**Comment by jamesknelson** [comment]
Just added a contributors guide to the README - please let me know if there's anything else I should add to it.

**Comment by jdiamond** [comment]
Thanks, I followed the new instructions and it worked except for 9 react-navi tests are failing with a jsdom error: `Not implemented: window.scroll`. I'll ignore those for the time being.

**Comment by jamesknelson** [comment]
Yep, those warnings can be ignored for the moment.

By the way, I've just pushed a change that affects the files that you'll need to change -- I updated my above comment with new filenames/line numbers.

**Comment by jdiamond** [comment]
Thanks for the pointers. I tried to take a crack at it, but had to give up after an hour of making no progress. You should add the help wanted label on this issue so somebody else can give it a go.

**Comment by jamesknelson** [comment]
Have just merged in a fix which changes the default behavior to omitting the trailing slash, and allows configuration via a `trailingSlash` option.

I'll be releasing this with 0.12.

**Comment by jdiamond** [comment]
Awesome, thank you! Sorry I couldn't figure it out.

**Comment by squarism** [comment]
I was getting `Error: Not implemented: window.scroll`.  Just for the boilerplate create-react-app "App doesn't crash" type test.  I have a test setup file that jest loads.  It has a global.window variable to handle this and like session storage.  I don't know of a better solution than this but I got rid of that error @jdiamond by doing this.  Jest runs without errors but I just got this working.

```
// setup.js - loaded by jest as part of setupFilesAfterEnv

// many other things like enzyme setup etc ...

global.window = {}
window.scroll = function () { }
// or window.scroll = () => { }
```

Maybe your project is slightly different, maybe this helps.  🎈

**Comment by jamesknelson** [comment]
This worked great. Thanks @squarism!

**Comment by lookfirst** [comment]
I love how great tips that totally just solve the issue, are just buried in some github comment somewhere...

**Comment by squarism** [comment]
@lookfirst Would you be horrified to know that I googled this and found my own comment and used it?  🌻

**Comment by lookfirst** [comment]
> @lookfirst Would you be horrified to know that I googled this and found my own comment and used it two years later? 🌻

We code in javascript, nothing horrifies us anymore. =)
