### ISSUE TITLE
navi-scripts serve not working

### ISSUE THREAD

**Issue by cevr** [frontarm/navi#59]
When running navi-scrips serve on a react-navi-app build, it gets stuck for many minutes with no resolution.

**Comment by jamesknelson** [comment]
What do you mean by "stuck" in this case? `navi-scripts serve` should just serve the `build` directory, so it doesn't usually output anything. Does it work when you do `react-scripts start`?

**Comment by cevr** [comment]
> What do you mean by "stuck" in this case? `navi-scripts serve` should just serve the `build` directory, so it doesn't usually output anything. Does it work when you do `react-scripts start`?

Sorry for the ambiguity. It definitely works with `react-scripts start`. I haven't tested it myself, but perhaps the issue is that if you use `navi-scripts serve` without  a production  build having already been created, it becomes stuck on deployment with no resolution. Even after I made a production build, it continued to be stuck on resolution.

Steps to reproduce:
- Create a fresh react-navi-app
- Run `yarn serve`

**Comment by jamesknelson** [comment]
Hmm I see. Perhaps a change to the logged console message would help?

Currently it is:

> Starting server on port 3000 to view production build...

I could change it to:

> Serving the current contents of your /build directory on port 3000...

Would this help?

**Comment by cevr** [comment]
> Hmm I see. Perhaps a change to the logged console message would help?
> 
> Currently it is:
> 
> > Starting server on port 3000 to view production build...
> 
> I could change it to:
> 
> > Serving the current contents of your /build directory on port 3000...
> 
> Would this help?

Ah okay, so it is working, but I assumed there would be another message that says "Serving!" or something. My bad 🙇

**Comment by jamesknelson** [comment]
No worries! If you can think of a clearer message, would you be able to make a PR? It should just be a single line change around here:

https://github.com/frontarm/navi/blob/master/packages/navi-scripts/lib/serve.js#L18
