### ISSUE TITLE
Errors importing as an ES module from unpkg

### ISSUE THREAD

**Issue by lukejacksonn** [frontarm/navi#63]
I have been trying to import navi directly from unpkg and have come across a few errors:

1. If you request `https://unpkg.com/navi@0.11.6?module` then this error appears:

<img width="742" alt="screen shot 2019-03-04 at 15 21 31" src="https://user-images.githubusercontent.com/1457604/53721099-f3ed2e00-3e94-11e9-8429-8a4e872ec903.png">

Apparently this is related to webpack https://github.com/webpack/webpack/issues/8838

2. If you specify the exact file `https://unpkg.com/navi@0.11.6/dist/es/index.js` then the above error disappears but then this error appears:

<img width="821" alt="screen shot 2019-03-04 at 15 28 22" src="https://user-images.githubusercontent.com/1457604/53721223-3dd61400-3e95-11e9-85ee-608f9bc6c8bf.png">

Apparently this is to do with navi having `history` as an optional dependency (for interoperability with react-router). Solving this issue is likely to negate issue 1.

**Comment by jamesknelson** [comment]
So the reason this error occurs is that Navi uses a `history` object internally. However, the only time that the `history` package is used is to create a history object when one isn't provided from the outside.

To solve this, we'd need to remove the dependency on `history` while still allowing a history object to be passed in as a prop. As such, there are two options:

1. Bundle `history` by source instead of importing it
2. When a history object isn't passed in via prop, use an internal stub that doesn't include all of the functionality of the main package.

The problem with either of these options is they add a lot of code to Navi that needs to be maintained. That said, option 2 would actually *decrease* bundle sizes for people not using react-router, as Navi probably doesn't need all the features that `history` provides.

I'm really not sure what approach to take here. Do you have any thoughts?

**Comment by lukejacksonn** [comment]
Option 2 sounds like the better option to me. I am lacking some context, but why would anyone want to use this solution in combination with react router and not just one or the other?

> use an internal stub that doesn't include all of the functionality of the main package.

An internal stub of the `history` package? Is there no way to make navi this work without that as a dependency at all (I haven't had time to get stuck into the codebase yet)?

**Comment by jamesknelson** [comment]
A lot of big projects are built around react-router. Allowing integration between the two makes it possible to start writing some routes with Navi in an existing project, without converting the whole thing up front.

As for why Navi relies on history, any router is going to need some way to interact with the browser history, as the raw history API leaves a bit to be desired. `history` also has the advantage of being able to prompt the user when they leave a page though, which is great if you have unedited text and accidentally press "back".

**Comment by lukejacksonn** [comment]
Makes sense.. so I am digging into this a bit more and the first thing I notice is that the error that the `failed to resolve history` error being is being thrown before I get chance to actually use navi (during import) .

My gut feeling here was passing in `history` could be made required; either you supply navi `Router` component with the instance of history that react-router gives you as a render prop.. or you import history yourself and pass it in as a prop. Something like:

```js
import createHistory from 'history/createBrowserHistory'
import { Router } from "navi"

const history = createHistory()
const routes = mount(...)

export default function App(props) {
  return (
    <Router routes={routes} history={history}>
      <Suspense fallback={null}>
        <View />
      </Suspense>
    </Router>
  )
}
```

This would mean that `history` is no longer a "dependency" of navi but navi does require you to pass in `history` as a prop – which takes away from that _works out of the box_ developer experience and could lead to version mismatches perhaps.

Not a satisfactory solution really 🤔 I will keep thinking!

**Comment by jamesknelson** [comment]
One possibility would be importing history using a conditional `require()` instead of a top-level import, and only doing so when `history` isn't supplied externally.

For webpack-bundled apps, this wouldn't change anything, but for pure ES modules apps like yours, it'd give you the option of importing history from somewhere else (e.g. a `<script>` tag) and passing it in -- preventing the `require()` from ever being executed. And given that `history` doesn't work with ES modules anyway, we wouldn't really be losing anything by using `require()` instead of `import`.

How's this sound?

**Comment by lukejacksonn** [comment]
That sounds pretty good! Would you prefer `require()` over `import()` given that the rest of the codebase uses ES imports?

Would it go here https://github.com/frontarm/navi/blob/master/packages/react-navi/src/History.tsx#L2

**Comment by jamesknelson** [comment]
In this case I'd prefer `require()` as it's synchronous. Changing it to use `import()` would require a lot of refactoring to use promises, whereas adding a `require()` in an if statement is just a few lines.

There are two place where you'd need to change it:

- https://github.com/frontarm/navi/blob/master/packages/navi/src/BrowserNavigation.ts#L54
- https://github.com/frontarm/navi/blob/master/packages/navi/src/MemoryNavigation.ts#L59

You only need to worry about `createMemoryHistory()` and `createBrowserHistory()` -- the `History` import is just a TypeScript interface, so it's removed from the generated code.

**Comment by jamesknelson** [comment]
@lukejacksonn I've just tried changing the `history` import to a `require()` statement, but it seems that unpkg still converts it into a module import which.

I'd like to remove the dependency on history completely before 1.0. To that end, f01a4311a92242d786e08184bb7d67df0ba7aae5 has deprecated access to `history`, in favor of accessing Navi's `route` objects or using the new `navigation.navigate()` method. Once `navigation.history` is gone, we can remove the history package in favor of direct interaction with the browser history API (unless a `history` object is supplied manually).

In the meantime, this feels more like an unpkg issue than a Navi issue, so I'm going to close this issue off.

**Comment by lukejacksonn** [comment]
Sorry I haven't had time to dig into this any more than I did!

 > but it seems that unpkg still converts it into a module import which.

As in, you were seeing unpkg make on the fly modifications to the file? I think that happens when you let it do the resolving (i.e. specifying `?module`). I believe you can avoid that by linking directly to the file you want manually like https://unpkg.com/navi@0.11.6/dist/es/index.js for example.

Maybe that will work for you with the `require` adaptation. Regardless I can fully get behind dropping history as a dependency. I have written a few routers in my time and as much as the history package was always tempting, I never did use it and still got out alive.

Thank you so much for your time and creating such an awesome lib!

**Comment by jamesknelson** [comment]
You're welcome 😄

I see - yeah I was using `?module`. You're right that it'd probably work if you just used the raw file, although now that I'm deprecating `navigation.history`, I think I might just wait until the version that removes the dependency completely.
