### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jbadeau** [frontarm/navi#70]
Hi,

Great work on navi but it would be really helpful to have a changelog to track what is fixed, changed, etc.

**Comment by jamesknelson** [comment]
This is a great idea, especially now that the API has started to settle down.

Will attempt to use [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) for the next release. Will leave this open until the process is working smoothly.

**Comment by th3fallen** [comment]
any updates on this? that would be great to have

**Comment by jamesknelson** [comment]
There haven't been many updates lately so I haven't had much to write, but I just manually added a CHANGELOG with the details of the latest published version. Will keep it up to date with any new changes.

**Comment by jbadeau** [comment]
Cool
