### ISSUE TITLE
Could you please add an example with astroturf and/or linaria (Zero runtime CSS-in-JS) 

### ISSUE THREAD

**Issue by VladSez** [frontarm/navi#77]
https://github.com/4Catalyzer/astroturf
https://github.com/callstack/linaria

**Comment by jamesknelson** [comment]
I'm pretty sure this is currently impossible without ejecting from create-react-app, and I don't really want to start messing with build systems for examples.

If you can get it working without unejected CRA feel free to re-open and submit a PR, but otherwise I'll close this for now.
