### ISSUE TITLE
Allow for functional access to router/navigation information for class components

### ISSUE THREAD

**Issue by th3fallen** [frontarm/navi#80]
Hopefully im missing something, but we have a very large application that is 99% class components, im attempting to migrate to your router because it looks to be quite good.

but for the following example i cannot find a way to recreate this with navi.

```
  componentDidUpdate() {
    setIntercomVisibility(this.props.accountPlan && this.props.location.pathname != '/scheduler/onboarding');
  }
```

previously with react-router we leveraged the `withRouter` HOC, but im not sure if there's a way but it would be amazing if we could simply call `useCurrentRoute` or some mutation of that that worked with classes.

Hopefully this isnt a big ask and im just overlooking something simple.

Thanks again, and great work on this router it looks extremely promising!

**Comment by jamesknelson** [comment]
So the way I do this when using classes is I just create a wrapper function component, something like this:

```js
function MyComponent(props) {
  let route = useCurrentRoute()
  return <MyComponentImpl {...props} route={route} />
}

class MyComponentImpl extends React.Component {
  componentDidUpdate() {
    //...
  }
}
```

I haven't added any HoCs to Navi itself, as I feel like wrapper components with hooks are a far cleaner option. But if you want a `withCurrentRoute` HoC, then it should be pretty easy to create one yourself. The simplest way is to use `useCurrentRoute()`, but that only works with React 16.8+. If you're using an older version of React, you can also use the <CurrentRoute> component with a render prop, which looks something like this:

```js
import { CurrentRoute } from 'react-navi'

function withCurrentRoute(WrappedComponent) {
  return function WrapperComponent(props) {
    return <CurrentRoute children={route =>
      <WrappedComponent {...props} route={route} />}
    />
  }
}
```

**Comment by th3fallen** [comment]
Thanks for the answer, that should work well. And while i agree hooks are much cleaner, it does alienate a large portion of users who still use class based components.

But again, great work on this lib!
