### ISSUE TITLE
Can we use useLoadingRoute ourselves?

### ISSUE THREAD

**Issue by remotealex** [frontarm/navi#82]
Hello! I was wandering if we could _hook_ into `useLoadingRoute` ourselves somehow?

Currently I've got a centralised route loading indicator at the `App` level using `useLoadingRoute` which is working great for `getData` calls.

However, in a nested route I'm doing some data loading within `useEffect` and I'm having to duplicate my loading indicator inside this component as this data loading has no connection to `useLoadingRoute`. It would be sweet to be able to trigger `useLoadingRoute` from within my `useEffect` call.

I hope that makes sense! Cheers

**Comment by jamesknelson** [comment]
Effectively all `useLoadingRoute()` does is subscribe to the current Navi context via `navigation.subscribe()`, and check whether `route.type === "busy"`. You can see this here: https://github.com/frontarm/navi/blob/master/packages/react-navi/src/NaviProvider.tsx#L28

You could write a similar component to `NaviProvider` that just passes loading status down via context, and allows you to set it yourself.

I'm not sure I'd want to add this to Navi proper as I feel like a better long term solution is going to be tighter integration with Suspense, so I'm going to close this issue. But if you have any questions about the DIY approach, let me know here and I'll see what I can do.
