### ISSUE TITLE
Optional parameters in routes

### ISSUE THREAD

**Issue by th3fallen** [frontarm/navi#85]
Is it possible to have an optional route parameter?

in react-router we had routes like this...
route url `/requests/shift(/:id)` which allowed us to both navigate to `/requests/shift` and `requests/shift/1`

im not seeing a documented way to do this with navi, am i just missing something?

**Comment by jamesknelson** [comment]
It's possible to achieve a similar result by passing the same matcher to both `/` and `/:id`, like so:

```js
let matcher = map(({ params }) =>
  route({
    view: <div>Hello {params.id || 'world!'}</div>
  })
)

mount({
  '/': matcher,
  '/:id': matcher,
})
```

I don't think this behaves *exactly* the same as optional routes, but does it cover your use case?

**Comment by th3fallen** [comment]
I think that should work fine, it would be amazing if I'm the future there was better support for this.

Thanks again for the help!

**Comment by jamesknelson** [comment]
If you wanted to add this feature I'd be open to a PR :-)

**Comment by th3fallen** [comment]
Good to know, i'll give that a shot

**Comment by th3fallen** [comment]
@jamesknelson sorry for the late follow up but for a newby to your codebase could you give me a pointer of a starting point?
