### ISSUE TITLE
Question: Is it possible to change query params without reloading route?

### ISSUE THREAD

**Issue by szimek** [frontarm/navi#88]
I've got a strange use case - I've got a checkout form where user can select a product and enter a discount coupon. Now, whenever user changes a selected product, or enters a coupon, I'd like to persist this info in query parameters, so that when user reloads the page, or sends its url to someone else, they will see the page in exactly the same state. However, if I use `navigation.navigate` (or `history.push`) to change query params, it triggers route change and executes routing code again and I'd like to avoid that. Angular 1.x router has `reloadOnSearch` option that could be set to `false`, to avoid reloading route on query params change. Is it somehow possible to do the same thing with navi?

**Comment by jamesknelson** [comment]
While it's not currently possible to avoid refreshing the route on reload, it *is* possible to cache data between refreshes by passing a `state` object to `route({ ... })`, and by reading from `request.state`. This makes it possible to avoid fetching the same data twice when you expect the query to change.

Unfortunately this is still a pretty low level API. I'd like to find a higher-level way to allow for data to be cached between refreshes like this, although I'm not exactly sure how it'll end up looking yet.

**Comment by szimek** [comment]
@jamesknelson Thanks for the tip! It works! It would be great if it could not refresh route on reload, because we're currently doing waaaay to much stuff in the route itself, so I'd like to avoid running this code completely, but at least I've got a working workaround.

I had to update navi from 0.11.x to 0.12.x to be able to set route's state. One thing that also seems to change (BTW. is there a CHANGELOG somewhere?), is that before when I was using `history.push` directly, it did not trigger route change if the url hasn't changed. Now I'm using `navigation.navigate` and I need to check if it has changed, otherwise I'm getting an infinite loop.

Thanks again!

**Comment by jamesknelson** [comment]
The infinite loop sounds like a problem that needs fixing - is there any chance you could create a separate issue for that with a minimal reproduction?

As for stopping running routes themselves, it sounds like we might need something like React's `shouldComponentUpdate`. I'm not exactly sure how to go about this, but if you have any ideas in terms of design then I'd be keen to hear them.

Re: changelog, will be adding one for all future changes.

**Comment by szimek** [comment]
One more use case for being able to change query params without reloading a route or redirecting. We've support PayPal payments and we need to pass a failure url that PayPal will redirect to in case of, well, failure. In our case the failure url is the checkout page, where user initiates PayPal payment. We only append a query param with an error message to it and PayPal appends a `token` query param. In our old Angular app, we checked for these query params on page load, showed an error message and removed them. This way when user would e.g. reload the page, they wouldn't see the same error message again. Because this logic happened in a component, we could already preselect PayPal as preferred payment when these query params were present. 

In navi, it looks like I can redirect to the same url without these query params, but then I won't know that user had PayPal selected. Not a big deal, but would be useful to support this use case.

**Comment by jamesknelson** [comment]
I've come across a similar problem so I definitely want to find a good solution for this. The issue is that HTTP redirects on the server can't pass state through, and I want the API to work across both SSR and the client.

I have a few ideas about this, just need to find the time to put them into a proposal or some code.
