### ISSUE TITLE
All links created with <Link> have context="[object Object]" attribute in HTML

### ISSUE THREAD

**Issue by szimek** [frontarm/navi#90]
It looks like `context` prop is unnecessarily passed to `<a>` tag, because all links get `context="[object Object]"` attribute. This issue is present even on Navi docs page in all demos.

BTW. Somewhat related, but not really: when there's no CSS class, the `class` attribute is still present and gets a single space as its value. It could probably be removed completely in this case.

**Comment by mrtnbroder** [comment]
I have this on not just links, but all components where I pass a context.

**Comment by szimek** [comment]
What do you mean by "components" here? I'm talking about `<a>` tag that looks like e.g. this:
```html
<a href="/" context="[object Object]" class=" ">Link</a>
```
I guess if you pass context to any other html tag e.g. 
```jsx
const SomeContext = React.createContext();
const SomeComponent = () => (
  <div context={SomeContext} />
);
```
it would also generate a similar html code. The thing is that `context` should not be passed to html tags, only components. Most likely the spread operator is used when passing props to `<a>` tag in `Link` component (or one of its children) and they include `context`, which is not necessary for `<a>` tag.

**Comment by jamesknelson** [comment]
This definitely looks like it needs a fix. Would be happy to accept a PR, otherwise will try and get this done on the next minor update.
