### ISSUE TITLE
Animated Transitions

### ISSUE THREAD

**Issue by loganpowell** [frontarm/navi#95]
So happy to see a router library fully embrace latest/greatest features of React and - most importantly - the reality of async.

Question: Do you have any examples for animating between route transitions?

**Comment by loganpowell** [comment]
If you're looking for inspiration for creating an example, this one would blow everyone's socks off:

https://css-tricks.com/native-like-animations-for-page-transitions-on-the-web/

**Comment by jamesknelson** [comment]
No examples of animating route transitions just yet. It's definitely something that needs to be done, although right now it's not a very high priority.

Would definitely accept a PR in the examples folder though!

**Comment by loganpowell** [comment]
I am willing to give it a go. Just want to make sure it's possible before I get started. Is there anything I should be aware of within `navi` before trying to implement the example above?

**Comment by jamesknelson** [comment]
The only thing to keep in mind with Navi is that all the actual state is stored externally from React. The `<View>` components just render your route views, so as long as they can be animated, you should be ready to go.

**Comment by jamesknelson** [comment]
I've just released a new hook with 0.13.0-alpha.0 that should make this super easy with a library like react-spring.

The new `useViewElement()` hook returns the element that would have been rendered by `<View />`. This key here is that the returned element does not depend on context, so you can just pass it into a react-spring `useTransition` and key on `useCurrentRoute().url.pathname`.

If you're still interested in giving this a go, this should make things a *lot* easier.

**Comment by jamesknelson** [comment]
Just published a guide on this at https://frontarm.com/navi/en/integrations/react-spring/
