### ISSUE TITLE
Use with react router documentation demo crashes

### ISSUE THREAD

**Issue by vongohren** [frontarm/navi#97]
The example at use with react router crashes:

<img width="1673" alt="Image of the error" src="https://user-images.githubusercontent.com/1012055/59189469-664b6980-8b7a-11e9-9979-fc64ea408d6c.png">

**Comment by jamesknelson** [comment]
Thanks for pointing this out!

This has been resolved after upgrading Navi 0.12.8 to use History 4.9.0. Should be live on the site in 5 minutes or so.
